
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "atlas_local"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "3.0.0"
napi-derive = "3.0.0"

[dependencies.atlas-local]
git = "ssh://git@github.com/mongodb/atlas-local-lib.git"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
